# Generated by Django 3.2.12 on 2022-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=60)),
                ('studentid', models.CharField(max_length=60)),
                ('openness', models.CharField(max_length=60)),
                ('neuroticism', models.CharField(max_length=60)),
                ('conscientiousness', models.CharField(max_length=60)),
                ('agreeableness', models.CharField(max_length=60)),
                ('extraversion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('resume', models.FileField(upload_to='documents')),
            ],
        ),
    ]
