# Generated by Django 3.2.12 on 2022-06-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='agreeableness',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='answermodel',
            old_name='conscientiousness',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='extraversion',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='neuroticism',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='openness',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='postid',
        ),
    ]
